# This docker-compose file is only for local development purposes.
version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.development
    depends_on:
      - database
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ./:/opt/formsg
      - /opt/formsg/node_modules
    ports:
    network_mode: 'service:backend' # reuse backend service's network stack so that it can resolve localhost:5156 to mockpass:5156

  database:
    image: 'bitnamilegacy/mongodb:4.4'
    environment:
      - MONGODB_DATABASE=formsg
      - MONGODB_ADVERTISED_HOSTNAME=database
      - MONGODB_REPLICA_SET_MODE=primary
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mongodb_data:/bitnami/mongodb
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - '27017:27017'

  localstack:
    image: localstack/localstack:3.3
    depends_on:
      - backend
    environment:
      - SERVICES=s3,sqs
      - DNS_ADDRESS=0
      - EXTRA_CORS_ALLOWED_ORIGINS=http://localhost:5173
    volumes:
      - ./.localstack/volume:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: 'service:backend' # reuse backend service's network stack so that it can resolve localhost:4566 to localstack:4566
    attach: false

  maildev:
    image: maildev/maildev
    ports:
      - '1080:1080'

  stripe-cli:
    image: stripe/stripe-cli
    command: 'listen --api-key ${STRIPE_API_KEY} --device-name ${STRIPE_DEVICE_NAME} --forward-to host.docker.internal:5001/api/v3/notifications/stripe'
    environment:
      - STRIPE_API_KEY
      - STRIPE_DEVICE_NAME=StripeWebhookListener

volumes:
  mongodb_data:
    driver: local

